const quotationMarks = {
    'Select language': 'No language selected.',
    'Afrikaans': '“…”',
    'Albanian': '„…“',
    'Amharic': '«…»',
    'Arabic': '«…»',
    'Armenian': '«…»',
    'Azerbaijani': '«…»',
    'Basque': '«…»',
    'Belarusian': '«…»',
    'Bosnian': '”…” or „…”',
    'Bulgarian': '„…“',
    'Catalan': '«…»',
    'Simplified Chinese': '“⋯”',
    'Traditional Chinese': '「⋯」',
    'Croatian': '„…”',
    'Czech': '„…“',
    'Danish': '»…« or “…”',
    'Dutch': '“…”',
    'English (UK)': '‘…’',
    'English (US, Canada)': '“…”',
    'Esperanto': '“…”',
    'Estonian': '„…“',
    'Filipino': '“…”',
    'Finnish': '”…”',
    'French': '« … »',
    'French (Switzerland)': '«…»',
    'Galician': '«…»',
    'Georgian': '„…“',
    'German': '„…“',
    'German (Switzerland)': '«…»',
    'Greek': '«…»',
    'Hebrew': '"…"',
    'Hindi': '“…”',
    'Hungarian': '„…”',
    'Icelandic': '„…“',
    'Ido': '« … »',
    'Indonesian': '“…”',
    'Interlingua': '“…”',
    'Irish': '“…”',
    'Italian': '«…»',
    'Italian (Switzerland)': '«…»',
    'Japanese': '「…」',
    'Kazakh': '«…»',
    'Khmer': '«…»',
    'Korean (North)': '《…》',
    'Korean (South)': '“…”',
    'Lao': '“…”',
    'Latvian': '“…” or „…“',
    'Lithuanian': '„…“',
    'Lojban': 'lu … li’u',
    'Macedonian': '„…“',
    'Maltese': '“…”',
    'Mongolian (Cyrillic script)': '«…»',
    'Mongolian (Mongolian script)': '⟪…⟫ (rotate 90 degrees, it\'s written vertically)',
    'New Tai Lue': '《…》',
    'Norwegian': '«…»',
    'Occitan': '«…»',
    'Pashto': '«…»',
    'Persian': '«…»',
    'Polish': '„…”',
    'Portuguese (Brazil)': '“…”',
    'Portuguese (Portugal)': '«…»',
    'Romanian': '„…”',
    'Romansh': '«…»',
    'Russian': '«…»',
    'Serbian': '„…”',
    'Scottish Gaelic': '‘…’',
    'Slovak': '„…“',
    'Slovene': '„…“',
    'Sorbian': '„…“',
    'Spanish': '«…»',
    'Spanish (Mexico)': '“…”',
    'Swedish': '”…”',
    'Tai Le': '《…》',
    'Tamil': '“…”',
    'Tibetan': '《…》',
    'Tigrinya': '«…»',
    'Thai': '“…”',
    'Turkish': '“…”',
    'Ukrainian': '«…»',
    'Urdu': '“…”',
    'Uyghur': '«…»',
    'Uzbek': '«…»',
    'Vietnamese': '“…”',
    'Welsh': '‘…’',
  };
  

const languageDropDown = document.querySelector('#languageDropDown');
const selectedOption = document.querySelector('#selectedOption');

languageDropDown.addEventListener('change', () => {
  selectedOption.textContent = quotationMarks[languageDropDown.value];
});
